var time=60;myApp=[{     question:'Pertanyaan',     options:['Option1','Option2','Option3','Obtion4','Option5'],     answer:0 },
                   {     question:'Pertanyaan',     options:['Option1','Option2','Option3','Obtion4','Option5'],     answer:0 },
                   {     question:'Pertanyaan',     options:['Option1','Option2','Option3','Obtion4','Option5'],     answer:0 },
                   {     question:'Pertanyaan',     options:['Option1','Option2','Option3','Obtion4','Option5'],     answer:0 },
                   {     question:'Pertanyaan',     options:['Option1','Option2','Option3','Obtion4','Option5'],     answer:0 },
                   {     question:'Pertanyaan',     options:['Option1','Option2','Option3','Obtion4','Option5'],     answer:0 },
                   {     question:'Pertanyaan',     options:['Option1','Option2','Option3','Obtion4','Option5'],     answer:0 },
                   {     question:'Pertanyaan',     options:['Option1','Option2','Option3','Obtion4','Option5'],     answer:0 },
                   {     question:'Pertanyaan',     options:['Option1','Option2','Option3','Obtion4','Option5'],     answer:0 },
                   {     question:'Pertanyaan',     options:['Option1','Option2','Option3','Obtion4','Option5'],     answer:0 }]
