var time=60;myApp=[{     question:'Seorang wanita, berusia 69 tahun, mengeluhkan jari tangan tremor  sejak 7 bulan yang lalu. Riwayat hipertensi, diabetes mellitus, dan stroke  disangkal. Pemeriksaan tanda-tanda vital didapatkan dalam batas  normal. Pemeriksaan fisik tampak tubuh condong ke depan, tremor  pada ujung jari dan bibir, gerakan halus dan lambat, serta terdapat  cogwheel phenomenon. Gangguan neurotransmitter apakah yang  menyebabkan gangguan di atas ? ',     options:['Adrenalin','Noradrenalin','Asetilkolin','GABA','Dopamin'],     answer:0 },

{     question:'Tn. Doni, 68 tahun, datang dengan keluhan nyeri pada pinggang  kanan yang menjalar ke tungkai bawah kanan. Nyeri disertai dengan  kesemutan hingga mata kaki sebelah dalam, dan jari-jari kaki. Nyeri  terjadi mendadak ketika pasien sedang bekerja. Pada pemeriksaan  fisik, didapatkan tanda-tanda vital dalam batas normal, Lasegue Test  (+), Patrick dan Kontra Patrick Test (+). Pada pemeriksaan neurologis  didapatkan penurunan refleks fisiologis patella dextra, refleks fisiologis  Achilles dextra normal. Di mana perkiraan lesi pada pasien tersebut ?',     options:['CRVO','NPDR','AMD','CRAO','PDR'],     answer:2 },

{     question:'Wanita usia 53 tahun mengeluh kedua mata merah dan perih sejak 5 hari yang lalu. Pasien juga mengeluh ada yang mengganjal dan sering keluar air mata. Pemeriksaan visus normal, TIO normal. Pemeriksaan segmen anterior didapatkan margo palpebra edema dan hiperemi (+) dengan krusta kekuningan (+) bulu mata tampak rontok (+). Tatalaksana pasien ini adalah...',     options:['Tepi palpebra di kompres hangat','Di cuci dengan menggunakan shampo bayi','Tepi palpebra dibersihkan dengan air hangat + antibiotik topikal','Sodium Hyaluronic topikal','Antihistamin topikal'],     answer:2 },

{     question:'Seorang bayi usia 2 bulan datang diantar ibunya karena terdapat benjolan kemerahan disebelah kelopak mata bawah mata kanan. Dokter curiga adanya sumbatan pada saluran air mata. <div class="separator" style="clear: both;"><a href="https://iili.io/whAmZu.png" style="display: block; padding: 1em 0; text-align: center; "><img alt="" border="0" width="320" data-original-height="362" data-original-width="572" src="https://iili.io/whAmZu.png"/></a></div> Pemeriksaan lanjutan yang tepat pada pasien ini adalah...',     options:['Schirmer test','Anel test','Fluoresein test','Uji fistel','Amsler grid'],     answer:1 },

{     question:'Anak usia 1 tahun dibawa orang tua nya ke dokter karena mata anaknya tampak juling. Di lakukan pemeriksaan dan kedua mata anak tampak seperti gambar di bawah.<div class="separator" style="clear: both;"><a href="https://iili.io/whAQvS.png" style="display: block; padding: 1em 0; text-align: center; "><img alt="" border="0" width="320" data-original-height="383" data-original-width="527" src="https://iili.io/whAQvS.png"/></a></div> Diagnosis pasien ini adalah...',     options:['Disfungsi kelenjar meibom','Blefaritis anterior seborroic','Koloboma','Blefaritis anterior stafilokok','Epikantus'],     answer:4 },

{     question:'Seorang bayi usia 3 bulan datang diantar ibunya yang khawatir timbul benjolan pada kelopak mata kanan anaknya yang berwarna merah terang seperti strawberry. Benjolan tersebut timbul 1 minggu setelah anaknya lahir dan makin lama makin membesar. Dokter melalukan pemeriksaan dan didapatkan gambaran seperti gambar <div class="separator" style="clear: both;"><a href="https://iili.io/wh5W0v.png" style="display: block; padding: 1em 0; text-align: center; "><img alt="" border="0" width="320" data-original-height="308" data-original-width="381" src="https://iili.io/wh5W0v.png"/></a></div>. Diagnosis pada pasien ini adalah ...',     options:['Moluskum kontagiosum','Nevus','Xantelasma','Kalazion','Hemangioma'],     answer:4 },

{     question:'Seorang pria usia 25 tahun datang dengan keluhan benjolan pada kelopak mata kiri bawah, keluhan dirasakan sejak 2 bulan ini. Benjolan dikatakan tidak nyeri, pandangan tidak buram, mata tidak kemerahan, tidak ada rasa gatal dan panas. Dari pemeriksan ophtalmologi didapatkan benjolan non hiperemis pada kelopak bawah mata kanan, visus kedua mata 6/6. <div class="separator" style="clear: both;"><a href="https://iili.io/wh5jJp.png" style="display: block; padding: 1em 0; text-align: center; "><img alt="" border="0" width="320" data-original-height="490" data-original-width="662" src="https://iili.io/wh5jJp.png"/></a></div> Kelainan yang terjadi pada pasien ini adalah …',     options:['Radang kronis granulomatosa kelenjar Meibom','Sumbatan pada kelenjar Zeiss-Moll','Infeksi pada kelenjar lakrimal','Infeksi pada palpebra','Sumbatan duktus nasolakrimal'],     answer:0 },

{     question:'Seorang bayi usia 2 bulan diantar ibunya ke dokter karena kedua mata anaknya terlihat putih. Ibu pasien mengatakan bahwa saat hamil anaknya ini, pernah cek lab di dapatkan Ig M dan Ig G Anti Toksoplasma (+). Hasil pemeriksaan didapatkan leukokoria (+) kedua mata, fundus reflek (-). Diagnosis pada pasien ini kemungkinan adalah...',     options:['Katarak senil','Katarak juvenil','Katarak kongenital','Katarak imatur','Katarak insipien'],     answer:2 },

 {     question:'Pasien usia 56 tahun datang dengan keluhan penurunan penglihatan pada mata kiri sejak 5 bulan yang lalu. Nyeri dan mata merah disangkal. Riwayat trauma pada mata disangkal. Pasien memiliki riwayat diabetes mellitus sejak 5 tahun yang lalu, tidak pernah berobat rutin. Pemeriksaan didapatkan mata tenang, visus ODS 0,5/1,0, Pada pemeriksaan fundus okuli didapatkan edema makula (+), tortous vein (+) Dot hemorrhages (+). Diagnosis pasien ini adalah ...',     options:['Retinopati hipertensi','Ablasi Retina','Age-related macular degeneration','Oklusi arteri retina sentral','Oklusi vena retina sentral'],     answer:4 },

{     question:'Seorang laki-laki usia 17 tahun mengeluh mata kanan merah sejak 1 hari yang lalu. Sebelumnya mata kanan nya terkena bola tenis saat bermain. Visus OS 6/6, OD 6/60. Pada mata kanan didapatkan konjungtiva bulbi hiperemi (+), COA dijumpai darah ¾ bagian. Pemeriksaan mata kiri normal. Diagnosis pasien ini adalah ... ',     options:['Hematoma palpebra','Hifema','Hematoma subkonjungtiva','Subluksasi lensa','Dislokasi lensa'],     answer:1 }]
